version: '3'
services:
  api:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - DB_FILE=/tmp/db.sqlite3
    restart: unless-stopped
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - app-volume:/tmp
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - DB_FILE=/tmp/db.sqlite3
    command: celery -A thena worker -l INFO
    depends_on:
      - redis
      - api
    volumes:
      - app-volume:/tmp

  redis:
    image: redis
    restart: unless-stopped

volumes:
  app-volume:
